language: java
java:
    - oraclejdk7
before_install:
    - git clone https://github.com/kd0kfo/crypttools.git
    - cd crypttools/java
    - mvn install
    - cd ../..
install:
    - cd java
    - cd core
    - mvn compile install
    - cd ../console
    - mvn compile 
